-- DEBUG sinks are independent of report.sql; create before deploying DEBUG connectors.
-- No DROP statements: preserve diagnostic history when rebuilding reports.

CREATE TABLE CONFLUENT.RHS2_R18_FBNK_EB_C005_DEBUG (
    RECID            VARCHAR2(255) NOT NULL,
    OP_TYPE          VARCHAR2(16),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    APPLICATION      VARCHAR2(4000),
    CUSTOMER         VARCHAR2(4000),
    DATE_LAST_UPDATE VARCHAR2(4000),
    CURR_ASSET_TYPE  VARCHAR2(4000),
    OPEN_BALANCE     VARCHAR2(4000),
    DEBIT_MVMT       VARCHAR2(4000),
    CREDIT_MVMT      VARCHAR2(4000),
    TYPE_SYSDATE     VARCHAR2(4000),
    CONSTRAINT PK_RHS2_R18_FBNK_EB_C005_DEBUG PRIMARY KEY (RECID)
);

CREATE TABLE CONFLUENT.RHS2_R25_FBNK_EB_C005_DEBUG (
    RECID            VARCHAR2(255) NOT NULL,
    OP_TYPE          VARCHAR2(16),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    APPLICATION      VARCHAR2(4000),
    CUSTOMER         VARCHAR2(4000),
    DATE_LAST_UPDATE VARCHAR2(4000),
    CURR_ASSET_TYPE  VARCHAR2(4000),
    OPEN_BALANCE     VARCHAR2(4000),
    DEBIT_MVMT       VARCHAR2(4000),
    CREDIT_MVMT      VARCHAR2(4000),
    TYPE_SYSDATE     VARCHAR2(4000),
    CONSTRAINT PK_RHS2_R25_FBNK_EB_C005_DEBUG PRIMARY KEY (RECID)
);
